kind: pipeline
name: default
steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags
- name: install-instantclient
  image: quay.io/tike/drone-install-instantclient:12.2
- name: test-init
  image: busybox
  commands:
  - chmod -R o+w /drone/src  
- name: test
  image: node:10
  user: node
  commands:
    - export OCI_LIB_DIR=$PWD/instantclient
    - export OCI_INC_DIR=$PWD/instantclient/sdk/include
    - npm install
    - npm run lint
#    - npm test
- name: docker 
  image: plugins/docker
  settings:
    repo: quay.io/tike/aleph-x-proxy
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch: [dev]  
    #branch: [master, test]
trigger:  
  event: [push, tag]  
image_pull_secrets:
- pull_docker_config
---
kind: secret
name: docker_username
data: G+1KIUuVpTOfH3hrlBZP+JYDllQA4o4Rxgo5+UX/8ivJ0tEc5QUml3jEMZ1B8fyS1DI1GK0DPscKe0b7ofMKQQ==
---
kind: secret
name: docker_password
data: 1qCWpQ9JE/VOt2OXjJpWShG6cmKGyCULlxELar9LVbcQddKME0kvPor/yBwl42sCk1pk92th6ZmSRG44MkzF69/igAh5EZyzW8FQ7bqgm6Q9hudHyq2jMFJUahM=
